#!/usr/bin/env python3
"""Reproduce Agentic Engineering clarity edits; --write guards later edits."""
import argparse, hashlib, html, json, re, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; HERE=Path(__file__).resolve().parent
BASE='51f2e9a3479a864bf1901aa9c8e3bfa4961bcac0'; NAME='agentic-engineering'
SECTION=re.compile(r'<section\b[^>]*>.*?</section>',re.S)
def esc(s): return html.escape(s,quote=True)
def sha(s): return hashlib.sha256(s.encode()).hexdigest()
def notes(s,t): return re.sub(r'data-speaker-notes="[^"]*"',lambda m:'data-speaker-notes="'+esc(t)+'"',s,count=1)
def patch(s,pattern,value):
 s,n=re.subn(pattern,lambda m:value,s,count=1,flags=re.S); assert n==1,pattern; return s
def bul(items): return '<ul class="bul reveal">'+''.join('<li>'+x+'</li>' for x in items)+'</ul>'
def cards(items): return '<div class="cards c'+str(len(items))+' reveal">'+''.join('<div class="tile"><h3 class="k">'+a+'</h3><p>'+b+'</p></div>' for a,b in items)+'</div>'
def code(t): return '<div class="code reveal">'+esc(t)+'</div>'
def table(headers,rows): return '<table class="tbl reveal"><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in r)+'</tr>' for r in rows)+'</tbody></table>'
def slide(label,title,content,note,speaker,theme='light',tag='Engineering practice'):
 return f'<section class="slide {theme}" data-label="{esc(label)}" data-speaker-notes="{esc(speaker)}"><div class="slide-content"><div class="slide-head reveal"><span class="snum">0</span><div class="crumb">{tag}</div></div><h2 class="reveal">{title}</h2>{content}<p class="note reveal">{note}</p></div></section>'
original=subprocess.check_output(['git','show',BASE+':'+NAME+'.html'],cwd=ROOT,text=True)
match=re.search(r'(<deck-stage\b[^>]*>)(.*?)(</deck-stage>)',original,re.S)
src={i:s for i,s in enumerate(SECTION.findall(match[2]),1)}; assert len(src)==60
e={}
def retained(i,title,items,note,speaker):
 s=src[i];s=patch(s,r'<h2 class="reveal">.*?</h2>','<h2 class="reveal">'+title+'</h2>')
 if items is not None:s=patch(s,r'<ul class="bul reveal">.*?</ul>',bul(items))
 s=patch(s,r'<p class="note reveal">.*?</p>','<p class="note reveal">'+note+'</p>'); return notes(s,speaker)
e[1]=notes(src[1].replace('Internal talk · September 2026','Revised October 2026').replace('self-verifying loops','bounded, verified work'),'Developer follow-up. One illustrative invoice task ties the talk together. No live demo or benchmark run is implied. We will explain the machinery, set a finish line, count cost and make the useful practices repeatable.')
e[2]=slide('The hook','A useful task has a finish line',cards([('Vague request','“Fix the invoice bug.” The agent has to infer both the rule and what counts as done.'),('Checkable request','“Apply the VAT rate from the order. Preserve the tests, run the invoice suite, and show the diff.”')]),'Illustrative comparison, not two measured runs. A clearer request makes the result easier to assess; it does not guarantee success.','Start with an invoice whose net amount is 100 and whose order specifies 21 percent VAT. The expected total is 121. Do not act out the second prompt as a guaranteed win. The point is that we can now inspect the change against an explicit rule.',theme='dark',tag='The invoice task')
e[3]=slide('Agenda','Build a loop you can trust enough to use',cards([('Understand the machinery','Model → harness → tool result.'),('Define and check done','Acceptance cases, limits and evidence.'),('Control the workload','Useful context, measured cost and reusable checks.')]),'One task throughout: correct the invoice total, then verify its CSV export.','The invoice calculation and export are two parts of the same example project. Use this route instead of seven chapter dividers. Supporting recipes are in the reference deck.',tag='Our route')
e[5]=retained(5,'The model generates one token at a time',[
 'Each step produces a distribution over possible next tokens; decoding chooses one.',
 'The prediction depends on learned patterns and the context available to that step.',
 'Tool calls are generated output too. A separate program handles their execution.'
], 'The animation is a simplified decoding example. It does not describe everything learned during training.', 'Keep the next-token animation. Do not equate a trained language model with a one-word phone keyboard or imply that next-token generation rules out learned reasoning capabilities.')
e[7]=retained(7,'Attention connects information in context',[
 'Attention layers combine information from token positions with different weights.',
 'Supply the VAT rule and relevant code. Availability in context still does not guarantee correct use.'
], 'Conceptual diagram: multiple heads and layers contribute. Context is an input you curate, not a literal program.', 'Use the invoice diagram to explain why relevant earlier facts can influence a later answer. Do not derive a fixed attention budget or quality threshold from softmax weights. Architecture and task both matter.')
e[7]=e[7].replace('Attention: it weighs every token','Attention connects information').replace('the newest token looks back at all of them — with different strengths','illustration: earlier tokens can influence the next prediction').replace('For the newest token the model weighs every earlier token in the context, with different strengths','Conceptual links from a later token to earlier invoice-related tokens; not measured attention weights')
e[10]=slide('Reasoning and effort','More reasoning is a setting to evaluate',code('Illustrative check, not a hidden reasoning trace:\n\nOrder: net 100.00; VAT rate 21%\nExpected total: 100.00 × 1.21 = 121.00\n\nNow check the rule, rounding and implementation.'),'More deliberation can help, and can add time and cost. Compare supported effort settings on the same acceptance cases.','This is an explanation a developer can check, not a transcript of private model reasoning. Arithmetic alone cannot establish the intended tax rule; the order record supplies it. More effort does not guarantee a better answer. Exact controls and treatment of reasoning tokens depend on provider and model.',theme='dark',tag='Model behavior')
e[14]=slide('Model, harness, client','Three parts, three different jobs',cards([('Model','Proposes text or a structured tool call.'),('Harness','Builds context, applies permissions and coordinates tool execution.'),('Client','The terminal, editor or web interface where you inspect and steer the work.')]),'For the invoice task: the model requests a test run; the harness arranges it; the client displays the result.','The model need not be rented or remote. This talk uses a common API-backed harness as its example. Tool execution can be local or remote, depending on the integration; compatibility across models and harnesses is not universal.',tag='The machinery')
e[15]=slide('Anatomy of a tool call','A tool result becomes evidence for the next step',code('Illustrative tool exchange — syntax varies by harness\n\nmodel   → request: run invoice tests\nharness → execute permitted command in test environment\ntool    → exit 1; expected 121.00, got 100.00\nmodel   → inspect the VAT calculation; propose a patch'),'A tool request is a proposal to execute. Permissions and the tool environment determine what actually happens.','The example command is pytest tests/test_invoice.py -q. A model can read tool output and still draw the wrong conclusion. Retain command, exit status and relevant output so another person can verify the claim.',theme='dark',tag='The machinery')
e[16]=retained(16,'The harness supplies context for each call',None,'Illustrative API-backed loop. History may be sent again, referenced through a stateful API, or compacted; it is not permanent model memory.','Follow the arrows once. These are illustrative token counts, not a captured trace. The three bars show the context growing as tools add evidence. Some APIs retain conversation state; caching, retention and learned model memory are different concepts.')
e[16]=e[16].replace('stateless server','API endpoint').replace('POST full context','send context').replace('Sequence over one session: you talk to the harness (client), which POSTs the full and growing context to the stateless model API (server) each turn, running tools locally in between','Illustrative sequence: the harness supplies growing context to an API and runs permitted tools between calls')
e[21]=retained(21,'Keep going, with a limit and a stop condition',[
 'The harness returns tool results so the model can choose the next step.',
 'A verifier checks the candidate result. Failed checks can trigger another attempt.',
 'Stop on success, exhausted budget, repeated failure or a required human decision.'
], 'For the invoice fix: at most three repair attempts, then report evidence and unresolved failures.', 'The animation explains the action/result cycle. A production loop also needs configured time, cost and permission limits. Do not imply that every harness automatically checks the goal or keeps running until success.')
e[23]=slide('Verifiers','A green check proves only what it checks',cards([('Behavior','VAT comes from the order; zero VAT and rounding cases pass.'),('Integrity','Existing tests remain meaningful. Inspect changed assertions and test discovery.'),('Acceptance','Review the diff and exported values against the task, including gaps in coverage.')]),'Exit code 0 is useful evidence. It is not proof that the full task is correct.','Have a check tied to each requirement. A build verifies buildability, not tax correctness; a screenshot comparison can miss incorrect exported data. Keep important acceptance checks outside the agent-editable path where practical.',tag='Define done')
e[24]=slide('Loop failure controls','Match each failure to a control',table(['Failure','Concrete control'],[
 ['Repeats the same failed repair','Limit attempts; require a new hypothesis before retrying.'],
 ['Weakens tests to make them pass','Review the test diff; run independent acceptance checks.'],
 ['Changes unrelated behavior','Scope allowed paths; inspect the complete diff.']
]),'Prompts help communicate these rules. Enforce the important boundaries in tools, permissions and review.','The original called both failures spec bugs. Failures can also arise from model behavior, tools or environment. Do not promise an ungameable prompt. The controls reduce risk and make failure detectable.',theme='dark',tag='Define done')
e[25]=slide('A bounded task contract','Make the acceptance contract explicit',code('GOAL: export invoice net, VAT and gross values to CSV.\nSCOPE: invoice export code; preserve existing tests.\nVERIFY: pytest tests/test_export.py -q\nCASES: 21% VAT, zero VAT, rounding, quoted CSV fields.\nLIMIT: three repair attempts; then stop and report.\nEVIDENCE: diff, command, exit status, failures and gaps.'),'Pair this request with an enforced runtime budget and a review of the resulting artifact.','An illustrative request template, not a command to run in this repository. Do not publish, commit or deploy as an implicit consequence of passing tests. The checks must exist and assert the intended behavior before the loop is trusted.',tag='The invoice task')
e[27]=retained(27,'A short message can carry a long history',None,'Illustrative input volumes, not a bill. Repeated history counts as input; cache hits may have a different rate.','Use the three bars for one example only. Summaries, context editing and stateful transport can change this shape. The cost calculation follows separately, so do not call these numbers measured or assume every token is charged at the uncached rate.')
e[27]=e[27].replace('EXAMPLE — three turns, payload by payload','ILLUSTRATIVE — three requests, including history').replace('why does auth fail?','why no VAT?').replace('"fix it"  (3 tokens)','"fix it"').replace('each turn\'s request contains everything from the previous turns plus a tiny new message','each request includes retained history and a new message')
e[29]=slide('Token volume and cost','Count each billing category separately',table(['Category','What to record'],[
 ['Uncached input','New input processed at its applicable input rate.'],
 ['Cache writes and reads','Separate token counts and the configured cache rates.'],
 ['Generated output','Output usage, including billable reasoning where applicable.']
]),'Bill = sum of each category’s tokens × its rate, plus any separate tool or service fees.','Input volume alone cannot establish the dominant cost. Output rates, reasoning usage, cache writes, cache hits, retries and tools all matter. Use provider usage records and avoid counting cached input twice. Subscription limits are a different accounting model.',tag='Count the work')
e[31]=slide('Worked cost example','One cache-hit request: about five cents',table(['Illustrative usage and rates','Cost'],[
 ['19,000 cached input × $0.20 / million','$0.0038'],
 ['3,700 new input × $4 / million','$0.0148'],
 ['1,600 output × $20 / million','$0.0320'],
 ['22,700 input + 1,600 output in total','<b>$0.0506</b>']
]),'Assumed rates, not a measured bill. Without the cache hit: $0.0908 input + $0.0320 output = $0.1228.','This example deliberately specifies an existing cache hit, no new cache-write tokens and no separate tool charges. Establishing the cache earlier also costs money. The original input line items summed to 22,709, not exactly 22,700; this version uses explicit rounded totals consistently. Compare a complete task, including cache warm-up and retries.',theme='dark',tag='Worked arithmetic')
e[32]=retained(32,'Caching reuses work on a matching prefix',[
 'A prompt cache can reuse computed state for eligible, matching earlier content.',
 'Keep reusable instructions stable. Changes can invalidate the affected prefix and later content.',
 'Inspect cache usage records: expiry, minimum length and provider rules affect whether you get a hit.'
], 'Animation shows prefix reuse. Its price label is illustrative; rates vary. Cached content still occupies context.', 'Keep the existing KV-cache animation as a conceptual example. Do not claim that harnesses never rewrite: compaction and corrections can be necessary. Cache behavior and pricing are provider specific. TTL and break-even arithmetic are in the reference deck.')
e[34]=slide('Useful context','Keep the facts that the next decision needs',cards([('Keep','The invoice rule, failing case, relevant code, decisions and latest test result.'),('Summarize or remove','Duplicate file dumps, stale logs and abandoned approaches, once their useful findings are captured.')]),'Watch for missed requirements and repeated work. There is no universal “dumb zone” or safe fill percentage.','Long-context performance varies by task, model, positions and distractors. Attention weights summing to one do not establish a single fixed reasoning budget. A handoff or compacted summary can omit important details: check that the acceptance contract and evidence survive.',theme='dark',tag='Context quality')
e[36]=retained(36,'Delegate a question; ask for evidence back',[
 'Fresh helpers need a self-contained task and relevant inputs. Forks can inherit existing history.',
 'Keep intermediate investigation in the helper’s context; return findings with file references.',
 'Review the result. Delegation adds coordination cost and does not itself isolate filesystem access.'
], 'Example return: VAT calculation locations, the failing path, supporting lines and unresolved questions.', 'The animation shows separation of intermediate output, not a guarantee of empty input context. Fresh agents also receive system instructions and tool definitions. Worktrees separate edits, not security boundaries. Avoid delegating a trivial step when coordination costs more than the work.')
e[30]=slide('Cost per accepted task','Measure the task, including the failed attempts',cards([('Same acceptance bar','Use representative invoice cases and the same permissions and tools.'),('Whole run','Record quality, elapsed time, all token categories, retries and review effort.'),('Repeat and compare','Repeat representative cases before changing the default configuration.')]),'A higher-priced model can finish in fewer attempts. Whether it costs less is a measurement, not a rule.','Remove the old benchmark collage and the arithmetic implying that five times cheaper tokens become dearer merely by using three times as many. Separate success rate from spend per successful attempt so failed runs do not disappear from the comparison.',tag='Model choice')
e[40]=slide('Routing and escalation','Escalate when the evidence points to a need',bul([
 '<b>Start:</b> use a configuration that has met the acceptance bar on similar work.',
 '<b>Diagnose:</b> missing facts, a broken tool and hard reasoning call for different fixes.',
 '<b>Compare:</b> try supported effort or model changes against the same checks and budget.'
]),'There is no universal “effort first” ladder. Re-evaluate defaults when the task or model changes.','A larger model cannot recover a missing business rule by thinking harder. Use the invoice task to distinguish an omitted VAT rate from a difficult code path. Cache changes and extra review time belong in the comparison.',theme='dark',tag='Model choice')
e[42]=slide('Worker and reviewer','Assign a role and a return contract',cards([('Worker','Implement the bounded invoice change. Return the diff, test output and known gaps.'),('Reviewer','Check the tax rule, changed tests and edge cases. Return findings with evidence and severity.')]),'Choose configurations from measured performance in each role. A second model’s opinion is not a verifier.','This preserves the useful advisor/executor idea without a vendor-specific command or hierarchy. The reviewer can miss the same issue as the worker. Require actionable findings and let deterministic checks carry the claims they can actually establish.',tag='Split the work')
e[46]=retained(46,'One workflow for the invoice change',[
 '<b>Explore:</b> independently inspect the rule, calculation and export path; return evidence.',
 '<b>Plan and build:</b> reconcile findings, then give one owner the implementation.',
 '<b>Verify:</b> run acceptance checks and inspect the diff. Retry only within the remaining budget.'
], 'Pass evidence between stages. Parallelize independent investigation; coordinate edits and integration.', 'Use the existing workflow diagram with role labels rather than brand tiers. Each stage needs explicit inputs; a fresh context is optional, not automatic. The retry edge is bounded at three repair attempts. Passing tests leads to review, not automatic publication.')
e[46]=e[46].replace('Workflows · dynamic workflows','Workflows').replace('parallel explore on haiku, plan on fable, implement on opus, verify with tests, looping back on failure','parallel investigation, planning, implementation, tests and review, with bounded repair on failure').replace('explore · haiku','inspect rule',1).replace('explore · haiku','inspect calc',1).replace('explore · haiku','inspect export',1).replace('plan · fable','plan').replace('build · opus','build').replace('>retry<','>if budget<').replace('pass ✓ done','pass → review')
e[48]=slide('Choose the workflow','Use the simplest shape that fits',table(['Task shape','Starting point'],[
 ['Explain the VAT rule','One question with the relevant source.'],
 ['Fix the invoice calculation','One agent with tools and acceptance checks.'],
 ['Repeat a repair cycle','A bounded loop with a meaningful stop condition.'],
 ['Investigate independent areas','Helpers with explicit inputs, returns and an integration owner.']
]),'Add orchestration when it resolves a real bottleneck. Measure its coordination cost too.','This is an engineering choice, not a product command catalogue. Multi-agent work is useful for independent investigation and separately owned edits, but parallel work still needs someone accountable for integration.',theme='dark',tag='Split the work')
e[50]=slide('Project instructions','Store the rules needed on most tasks',code('# Project instructions — illustrative invoice repository\n- Test with: pytest tests/test_invoice.py -q\n- VAT rates come from the order record.\n- Preserve existing assertions; explain test changes.\n- Ask before changing the stored invoice schema.'),'Use the instruction-file convention your harness actually loads. Keep standing rules short and specific.','Examples include CLAUDE.md and AGENTS.md, but discovery and precedence differ by harness. Do not claim a universal fallback or import rule. A file only helps when its relevant instructions enter the active context.',tag='Make it repeatable')
e[52]=slide('A verification skill','Save the repeated invoice check as a skill',code('invoice-check/\n  SKILL.md     when to use it + verification procedure\n  scripts/     optional deterministic checks\n  references/  VAT and rounding rules'),'<b>Procedure:</b> inspect the diff → run the cases → report evidence and gaps.','Keep the verification example consistent with the talk. A skill describes a repeatable procedure; it does not make the agent or the tests infallible. Discovery metadata and loaded content both have context costs. A concrete Claude Code file example is in the reference deck.',theme='dark',tag='Make it repeatable')
e[55]=slide('One skill system','Connect a few procedures with explicit outputs',cards([('Plan the change','Input: invoice defect.<br>Output: rule, scope and acceptance cases.'),('Implement and check','Input: accepted plan.<br>Output: patch, tests and unresolved issues.'),('Review and record','Input: patch and evidence.<br>Output: reviewed result and a reusable lesson.')]),'Teach the workflow through its outputs. Add a new skill only when a repeated need justifies it.','This is our illustrative invoice skill system, not a claim that a named public skill package exposes these exact commands. Preserve a useful lesson only when it is accurate and has a clear retrieval path. Additional examples are linked in reference material.',tag='Make it repeatable')
e[57]=slide('Share the procedure','Package useful checks for the team',cards([('Skill','The repeatable invoice-check procedure and supporting files.'),('Plugin or shared package','A versioned way to distribute the procedure and supported integrations.')]),'Test discovery and behavior in a clean session before sharing. Installation does not replace review or permission boundaries.','The concrete publication recipe is optional reference material. Keep this explanation independent of a particular marketplace layout. A plugin can distribute more than skills; supported component types depend on the host.',theme='dark',tag='Make it repeatable')
e[59]=slide('Next task','Give the next task a checkable finish',bul([
 '<b>Define done:</b> name the behavior, scope, acceptance cases and stop limit.',
 '<b>Keep evidence:</b> inspect the diff and actual check results; report what remains unverified.',
 '<b>Measure and reuse:</b> record total task cost, then save the check you repeat.'
]),'<a href="agentic-engineering-reference.html">Optional reference: arithmetic, workflow sketch and skill publication</a>','Ask the audience to apply the contract to their next real task. The durable practice is bounded work with useful context and evidence, not a fixed vendor hierarchy.',tag='Take it back to work')
source_cards=cards([('Mechanisms','<a href="https://arxiv.org/abs/1706.03762">Attention Is All You Need</a><br><a href="https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents">Context engineering</a><br><a href="https://www.trychroma.com/research/context-rot">Context-length experiments</a>'),('Implementation details','<a href="https://platform.claude.com/docs/en/build-with-claude/prompt-caching">Prompt caching and usage</a><br><a href="https://code.claude.com/docs/en/sub-agents">Subagents and forks</a><br><a href="https://code.claude.com/docs/en/skills">Skills</a>')])
e[60]=slide('Sources','Questions? Check the evidence.',source_cards,'Primary sources checked 3 October 2026. Worked examples are illustrative. <a href="https://github.com/davidbudac/agentic-talks">All decks</a>.','Sources support the mechanisms and implementation qualifications. No paid provider experiments were performed for this revision. The old benchmark and model-price grids are omitted; their original text remains in Git. Reference material contains additional links for publication and learning.',theme='dark',tag='Sources')
# Optional material: revised recipes, not an archive of unsupported rankings.
e[8]=slide('Explore a transformer','Watch the mechanism, then inspect the code',cards([('Interactive explanations','<a href="https://poloclub.github.io/transformer-explainer/">Transformer Explainer</a><br><a href="https://bbycroft.net/llm">LLM Visualization</a>'),('Build a small model','<a href="https://karpathy.ai/zero-to-hero.html">Neural Networks: Zero to Hero</a><br>Follow a small model from training to generation.')]),'Optional learning links. A small teaching model does not represent every production architecture.','Use outside the spoken path. The links are retained as learning resources, not audited or timed course recommendations.',tag='Further exploration')
e[18]=slide('Request anatomy','Inspect what actually enters a request',bul(['Standing instructions and applicable project rules.','Tool definitions and relevant skill content.','Retained conversation, selected files and tool results.','The current user message.']),'Use a request inspector or provider token counters for real sizes. Avoid summing overlapping categories.','The former twenty-thousand-token breakdown was an illustration presented as an actual harness turn. This version teaches which categories to inspect without asserting measured sizes.',theme='dark',tag='Context reference')
e[28]=slide('Growth arithmetic','Growing history can produce quadratic input volume',code('Assume n calls; initial input B; each call adds d tokens.\nNo pruning, compaction or window cap in this toy model.\n\nInput at call k = B + (k − 1)d\nTotal input     = nB + d × n(n − 1) / 2\n\nB = 5,000; d = 2,000; n = 10\nLast call = 23,000; total input = 140,000 tokens.'),'This is an input-volume model. Apply actual cache, output and tool rates to calculate the bill.','Do not call it a measured session, and do not claim wall time or billed cost must follow the same curve. The expression counts the input to every call under the stated constant-growth assumptions.',tag='Worked arithmetic')
e[33]=slide('Cache break-even','Include the write before counting savings',code('Same eligible prefix; all later requests hit the cache.\nNormalize ordinary input cost to 1 per request.\n\nTotal cached cost = w + (n − 1)r\nCaching saves when w + (n − 1)r < n.\n\nExample r = 0.10:\nw = 1.25 → savings at 2 requests\nw = 2.00 → savings at 3 requests'),'Illustrative multipliers: verify model, platform, TTL and expiry rules. A cache miss changes the calculation.','The examples match common Claude cache-write multipliers, but reads differ across models. Cache entries must exist and remain eligible. With a 0.10 read multiplier, two requests at a double-price write cost 2.10 versus 2.00 uncached, so three are needed. Excludes varying tails, output and tool costs.',theme='dark',tag='Worked arithmetic')
e[47]=slide('Workflow sketch','Make the retry edge explicit',code('PSEUDOCODE — not a harness API\n\nfindings = investigate(rule, calculation, export)\nplan = reconcile(findings, acceptance_cases)\nlatest_failures = []\nfor attempt in range(3):\n    patch = implement(plan, latest_failures)\n    result = run_acceptance_checks(patch)\n    if result.passed: return request_review(patch, result)\n    latest_failures = result.failures\nreturn report_blocked(latest_failures)'),'Use enforced tool, time and cost limits around the workflow. Assign an owner to integration.','A shape to discuss, not runnable Python or a product command. The workflow starts with an empty failure list and known acceptance cases. Passing checks returns a review candidate. Stop if a required permission or missing fact prevents a meaningful next step.',tag='Workflow reference')
e[53]=slide('Skill file example','An invoice-check skill for Claude Code',code('---\nname: invoice-check\ndescription: Verify changes to invoice totals or CSV export.\n---\n1. Read the invoice rule and inspect the proposed diff.\n2. Run the invoice and export tests; keep the actual output.\n3. Check VAT, rounding and CSV escaping coverage.\n4. Report findings, exit status and untested cases.'),'Example path: <code>.claude/skills/invoice-check/SKILL.md</code>. Check discovery in a fresh session.','The paths and frontmatter are Claude Code examples checked against its skills documentation. Description-based discovery is not guaranteed on every phrasing. Invoke the skill explicitly if needed and test its behavior. This slide does not create or run a skill.',theme='dark',tag='Skill reference')
e[56]=slide('Further skill systems','Read the procedures before adopting the system',cards([('Matt Pocock’s skills','<a href="https://github.com/mattpocock/skills">Source repository</a><br>Inspect how each skill defines its trigger, procedure and output.'),('Compound Engineering','<a href="https://github.com/EveryInc/compound-engineering-plugin">Source repository</a><br>Inspect how planning, implementation and captured lessons connect.')]),'Optional source examples. Commands and package contents change; adapt and test the parts you choose.','Retained as links, not a current command catalogue or endorsement of every instruction. Our main talk uses the invoice example so these external systems are not a prerequisite.',tag='Further exploration')
e[58]=slide('Plugin publication recipe','Package, test, then share',code('my-plugin/\n  .claude-plugin/plugin.json\n  skills/invoice-check/SKILL.md\n\n1. Give the manifest a name and version.\n2. Test locally: claude --plugin-dir ./my-plugin\n3. Review contents and pin the version to distribute.\n4. Publish through your team’s approved channel.'),'<a href="https://code.claude.com/docs/en/plugins">Plugin overview</a> · <a href="https://code.claude.com/docs/en/plugin-marketplaces">Marketplace setup</a>','Claude Code example, checked 3 October 2026. This is a recipe to read; no publication is performed. A marketplace needs its own listing and valid source paths. Confirm team permissions and review hooks or integrations before distributing. Installation steps belong with the chosen channel.',theme='dark',tag='Publication reference')
ORDER=[1,2,3,5,7,10,14,15,16,21,23,24,25,27,29,31,32,34,36,30,40,42,46,48,50,52,55,57,59,60]
REFS=[8,18,28,33,47,53,56,58,60]
css='''<style>
/* Clarity batch 2: use the existing fixed canvas and Ember tokens. */
.slide{--body-size:32px;--small-size:24px;--code-size:27px}
.slide a{color:var(--s-text);text-decoration:underline;text-underline-offset:3px}
.slide a:focus-visible{outline:2px solid var(--s-accent);outline-offset:4px}
.reference-banner{position:absolute;top:20px;right:96px;z-index:2;font:20px/1.3 var(--font-body);color:var(--s-muted)}
</style>'''
def prepare(s,old,new,reference=False):
 s=re.sub(r'(<span class="snum">).*?(</span>)',lambda m:m[1]+str(new)+m[2],s,count=1)
 s=s.replace('<section ',f'<section data-origin-slide="{old}" ',1)
 if reference:
  s=re.sub(r'(<section\b[^>]*>)',lambda m:m[1]+'<div class="reference-banner">Optional reference · <a href="agentic-engineering.html">Back to the talk</a></div>',s,count=1)
 return s
def output(sections,ref=False):
 s=original[:match.start(2)]+'\n\n'+ '\n\n'.join(sections)+'\n\n'+original[match.end(2):]
 s=s.replace('</head>',css+'\n</head>',1)
 s=s.replace('var current = 0, presenter = null, mouseT = null;',"var current = Math.max(0, Array.from(ds.querySelectorAll(':scope > section')).findIndex(function(s){ return s.hasAttribute('data-deck-active'); })), presenter = null, mouseT = null;")
 if ref:s=s.replace('<title>Agentic Engineering — basics for developers</title>','<title>Agentic Engineering — Optional Reference</title>')
 return s
cover=slide('Reference guide','Engineering reference',cards([('Use selectively','Cost derivations, a workflow sketch and the invoice-check skill.'),('Check before use','Product recipes reflect documentation checked 3 October 2026.')]),'<a href="agentic-engineering.html">Return to the 30-slide main talk</a>','Optional reference, not a continuation required for the main talk. Original material remains recoverable from the recorded baseline commit.',theme='dark',tag='Optional reference').replace('<h2 class="reveal">Engineering reference</h2>','<h1 style="font:var(--w-bold) 76px/1.1 var(--font-display);margin-bottom:32px">Engineering reference</h1>').replace('<span class="snum">0</span>','<span class="snum">1</span>')
outputs={NAME+'.html':output([prepare(e[i],i,n) for n,i in enumerate(ORDER,1)]),NAME+'-reference.html':output([cover]+[prepare(e[i],i,n,True) for n,i in enumerate(REFS,2)],True)}
MERGED={4:'Removed divider; agenda supplies the route.',6:'Removed inaccurate one-word keyboard analogy; model explanation is main 4.',9:'Reasoning transition merged into main 6.',11:'Reasoning claims and effort merged into main 6; model-specific billing omitted.',12:'Model-specific effort table replaced by main 6 and 21.',13:'Tools transition merged into main 7.',17:'Statelessness simplified and scoped in main 9.',19:'Loop transition merged into main 10.',20:'Repeated ladder removed; practical workflow choices are main 24.',22:'Unbounded shell loop removed; bounded contract and reference pseudocode replace it.',26:'Cost transition merged into main 14; quadratic cost claim corrected in reference 4.',35:'Delegation transition merged into main 19.',37:'Model catalogue removed; measurement replaces tier assumptions in main 20–22.',38:'Unverified benchmark table removed; measure representative work in main 20.',39:'Model/effort comparison merged into main 6 and 21.',41:'Fixed vendor hierarchy removed; use measured worker/reviewer roles in main 22.',43:'Orchestrator pattern merged into main 23.',44:'Cross-vendor wrapper recipe removed; not needed for the teaching outcome.',45:'Fixed role-to-tier table replaced by main 20–22.',49:'Persistence transition merged into main 25.',51:'Repeated skill motivation merged into main 26.',54:'Skill-system overview merged into the concrete example in main 27.'}
slide_map=[]
for i,s in src.items():
 slide_map.append({'original':i,'label':html.unescape(re.search(r'data-label="([^"]*)"',s)[1]),'main':ORDER.index(i)+1 if i in ORDER else None,'reference':REFS.index(i)+2 if i in REFS else None,'action':'rewritten' if i in e else 'merged/removed','reason':MERGED.get(i,'Revised for the shorter spoken path.' if i in ORDER else 'Revised supporting example or recipe in optional reference.')})
manifest={'baseline':BASE,'outputs':{k:sha(v) for k,v in outputs.items()},'metrics':{NAME:{'before_slides':60,'after_slides':len(ORDER),'reference_slides':len(REFS)+1}},'maps': 'batch2-slide-map.json'}
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');a=p.parse_args()
 if a.write:
  prior=json.loads((HERE/'batch2-manifest.json').read_text()) if (HERE/'batch2-manifest.json').exists() else {'outputs':{}}
  for file,content in outputs.items():
   target=ROOT/file
   if target.exists():
    allowed={sha(original)} if file==NAME+'.html' else set()
    allowed.add(prior['outputs'].get(file))
    if sha(target.read_text()) not in allowed:raise SystemExit('Refusing to overwrite later edits: '+file)
  for file,content in outputs.items():(ROOT/file).write_text(content)
  (HERE/'batch2-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
  (HERE/'batch2-slide-map.json').write_text(json.dumps({NAME:slide_map},indent=2)+'\n')
 print(json.dumps(manifest,indent=2))
